from __future__ import annotations

import math

# App metadata and routes
APP_TITLE = "photo-diff"
APP_VERSION = "0.1.0"
ROUTE_HEALTH = "/health"
ROUTE_COMPARE_RAW_IMAGES = "/compare-raw-images"
ROUTE_COMPARE_POINT = "/compare-point"
UVICORN_APP_FACTORY = "photo_diff.app:create_app_from_env"

# Environment variables
ENV_EMBEDDING_API_URL = "EMBEDDING_API_URL"
ENV_EMBEDDING_API_KEY = "EMBEDDING_API_KEY"
ENV_EMBEDDING_TIMEOUT_SECONDS = "EMBEDDING_TIMEOUT_SECONDS"
ENV_AERIAL_API_URL = "AERIAL_API_URL"
ENV_AERIAL_EXPAND_FACTOR = "AERIAL_EXPAND_FACTOR"
ENV_AERIAL_TARGET_SIZE_RATIO = "AERIAL_TARGET_SIZE_RATIO"
ENV_AERIAL_WMS_GEO_PATH = "AERIAL_WMS_GEO_PATH"
ENV_AERIAL_WMS_LIGHT_PATH = "AERIAL_WMS_LIGHT_PATH"
ENV_AERIAL_G2I_PATH = "AERIAL_G2I_PATH"
ENV_UVICORN_HOST = "UVICORN_HOST"
ENV_UVICORN_PORT = "UVICORN_PORT"
ENV_UVICORN_RELOAD = "UVICORN_RELOAD"

# Defaults
DEFAULT_TIMEOUT_SECONDS = 30.0
DEFAULT_ROTATION_SAFE_EXPAND_FACTOR = math.sqrt(2.0)
DEFAULT_AERIAL_EXPAND_FACTOR = DEFAULT_ROTATION_SAFE_EXPAND_FACTOR
DEFAULT_AERIAL_TARGET_SIZE_RATIO = 0.15
DEFAULT_UVICORN_HOST = "127.0.0.1"
DEFAULT_UVICORN_PORT = 8000
DEFAULT_UVICORN_RELOAD = False

# HTTP
HTTP_SCHEME_HTTP = "http://"
HTTP_SCHEME_HTTPS = "https://"
HTTP_CONTENT_TYPE_JSON = "application/json"
HTTP_HEADER_CONTENT_TYPE = "Content-Type"
HTTP_HEADER_AUTHORIZATION = "Authorization"

# Aerial
IMAGE_ID_TEMPLATE_TOKEN = "{image_id}"

# JSON payload keys
KEY_IMAGE = "image"
KEY_EMBEDDING = "embedding"
KEY_VECTOR = "vector"
KEY_DATA = "data"
KEY_IMAGE_ID = "image_id"
KEY_BBOX = "bbox"
KEY_URL = "url"
KEY_AZIMUTH = "azimuth"
KEY_LON = "lon"
KEY_LAT = "lat"
KEY_X = "x"
KEY_Y = "y"
